#pragma once

/*
 * Keep NKRO enabled by default
 */
#define NKRO_DEFAULT_ON true

/*
 * Replace QMK's stock Solid Reactive renderer while preserving the official
 * RGB_MATRIX_SOLID_REACTIVE mode ID.
 */
#define SOLID_REACTIVE SHARKOON_ORIGINAL_SOLID_REACTIVE
/*
 * Add and disable RGB effects to my preference.
 */

#define ENABLE_RGB_MATRIX_FLOWER_BLOOMING
#define ENABLE_RGB_MATRIX_STARLIGHT
#define ENABLE_RGB_MATRIX_STARLIGHT_SMOOTH
#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE
#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT
#define ENABLE_RGB_MATRIX_RIVERFLOW

#define PALETTEFX_PHOSPHOR_ENABLE

#define GRADIENT_UP_DOWN    SHARKOON_ORIGINAL_GRADIENT_UP_DOWN
#define GRADIENT_LEFT_RIGHT SHARKOON_ORIGINAL_GRADIENT_LEFT_RIGHT
#define TYPING_HEATMAP      SHARKOON_ORIGINAL_TYPING_HEATMAP
#define CYCLE_PINWHEEL      SHARKOON_ORIGINAL_CYCLE_PINWHEEL
#define CYCLE_SPIRAL        SHARKOON_ORIGINAL_CYCLE_SPIRAL
#define PIXEL_RAIN          SHARKOON_ORIGINAL_PIXEL_RAIN
