WS2812_DRIVER = custom
OPT_DEFS += -DWB32_DMA_REQUIRED

SRC += sharkoon_sgk50_s2.c

LTO_ENABLE = yes

# Common QMK features
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = yes
RAW_ENABLE = yes
SEND_STRING_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes
TRI_LAYER_ENABLE = yes

CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LAYER_LOCK_ENABLE = yes
REPEAT_KEY_ENABLE = yes